### ISSUE TITLE
immich v1.105 not compatibly with tool

### ISSUE THREAD

**Issue by robin2405** [v411e/ppim-migrator#4]
I get this error

Migrating favorites
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/robin/.local/lib/python3.10/site-packages/ppim-migrator/__main__.py", line 24, in <module>
    cli()
  File "/home/robin/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/robin/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/robin/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/robin/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/robin/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/robin/.local/lib/python3.10/site-packages/ppim-migrator/__main__.py", line 20, in migrate_favorites
    migrator.migrate_favorites()
  File "/home/robin/.local/lib/python3.10/site-packages/ppim-migrator/migrator.py", line 42, in migrate_favorites
    matching_uids = self._get_matching_uids(photo_file_list)
  File "/home/robin/.local/lib/python3.10/site-packages/ppim-migrator/migrator.py", line 79, in _get_matching_uids
    items: list = search_result.get("assets").get("items")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by v411e** [comment]
Whoops, thanks for reporting. Will look into it 👍

**Comment by v411e** [comment]
@robin2405 Could you try v0.0.3 and check if the issue got resolved? I updated the API to match the latest Immich API spec and a first test on my side was successful.

**Comment by robin2405** [comment]
i have now different error 

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/robin/.local/lib/python3.10/site-packages/ppim-migrator/__main__.py", line 2, in <module>
    from .migrator import Migrator
  File "/home/robin/.local/lib/python3.10/site-packages/ppim-migrator/migrator.py", line 100
    f"Added a match: {filename} (pp: {photo_file}, im: {
    ^
SyntaxError: unterminated string literal (detected at line 100)

**Comment by v411e** [comment]
Oh, looks like autopep8 introduced some syntax errors with misplaced line-breaks during auto-format. Should be fixed now. (v0.0.4)

**Comment by robin2405** [comment]
0.0.4 worked with 1.105 i check also 1.106 that is not working with 0.0.4

**Comment by v411e** [comment]
Alright, thanks for checking! Then I'll close this issue
